--- #YAML:1.0
name:               Weblogic-UserAdmin
version:            1.02
abstract:           Administration Functions For Weblogic 8.1 Automated
author:
    - David Peters (David.Peters@EssentialEnergy.com.au)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Distribution:  0.01
    Test::Simple:        0.44
    Test::Strict:        0.01
    WWW::Mechanize:      1.66
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
